import Head from 'next/head'
import React, { Fragment } from 'react';



export default function About() {
  return (
    <Fragment>
      <Head>
        <title>About </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <h1>about</h1>
    </Fragment>

  )
}
