import React, { useRef, useEffect, Fragment } from 'react';
import { withPageAuthRequired } from '@auth0/nextjs-auth0';
import Footer from '../components/Footer'
import Head from 'next/head'

import { AnimatePresence, motion } from 'framer-motion'
import Header from '../components/Header';

export default function Blog({ user }) {
    return (

        <Fragment>
            <Head>
                <title>JAG </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <AnimatePresence exitBeforeEnter>
                
                    <h1 data-testid="ssr-title">Blog Page</h1>
                    <div data-testid="ssr-text">
                        <p>
                            You can protect a server-side rendered page by wrapping the <code>getServerSideProps</code> function with{' '}
                            <code>withPageAuthRequired</code>. Only logged in users will be able to access it. If the user is logged
                            out, they will be redirected to the login page instead.{' '}
                        </p>
                        <p>
                            Protected server-side rendered pages automatically receive a <code>user</code> prop containing the user
                            profile.
                        </p>
                    </div>
                <div className="result-block-container" data-testid="ssr-json">
                    <div className="result-block">
                        <h6 className="muted">User prop</h6>
                        <h1>{user.name}</h1>
                    </div>
                </div>
        </AnimatePresence >
    </Fragment >
    
  );
}

export const getServerSideProps = withPageAuthRequired();
