import React, { useRef, useEffect, Fragment } from 'react';

import { AnimatePresence, motion } from 'framer-motion'
import { gsap } from 'gsap';
import Head from 'next/head'
import Header from '../components/Header'
import Hero from '../components/Hero'
import News from '../components/News'
import Banner from '../components/Banner'
import Info from '../components/Info'
import LogoSection from '../components/LogoSection'
import Footer from '../components/Footer'


export default function Home() {

  return (

    <Fragment>
      <Head>
        <title>JAG </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AnimatePresence >

        <Hero
        />
        <News
        />
        <Banner
        />
        <Info
        />
        <LogoSection
        />
      </AnimatePresence >

    </Fragment>
  )
}
